name: Gitee repos mirror periodic job
on:
  push:
    # Uncomment the following line to trigger on every push
    # branches:
    #   - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.01
      #代表我们用的仓库，不用同步
      with:
        src: github/guysbeing
        dst: gitee/yp-l
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org

